//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildUtil.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuildUtil.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 [j]追加[e]Add[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_BUTTON_ADD {
            get {
                return ResourceManager.GetString("CDF_BUTTON_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   [j]キャンセル[e]Cancel[/]   的本地化字符串。
        /// </summary>
        internal static string CDF_BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("CDF_BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    [j]完  了[e]Complete[/]    的本地化字符串。
        /// </summary>
        internal static string CDF_BUTTON_COMPLETE {
            get {
                return ResourceManager.GetString("CDF_BUTTON_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]削除[e]Delete[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_BUTTON_DELETE {
            get {
                return ResourceManager.GetString("CDF_BUTTON_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]編集[e]Edit[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_BUTTON_EDIT {
            get {
                return ResourceManager.GetString("CDF_BUTTON_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   [j]修正する[e]Modify[/]   的本地化字符串。
        /// </summary>
        internal static string CDF_BUTTON_MODIFY {
            get {
                return ResourceManager.GetString("CDF_BUTTON_MODIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    O  K    的本地化字符串。
        /// </summary>
        internal static string CDF_BUTTON_OK {
            get {
                return ResourceManager.GetString("CDF_BUTTON_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   [j]処理中[e]Wait[/]... 的本地化字符串。
        /// </summary>
        internal static string CDF_BUTTON_SENDING {
            get {
                return ResourceManager.GetString("CDF_BUTTON_SENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 　[j]最近の候補[e]Recent Candidates[/]:  的本地化字符串。
        /// </summary>
        internal static string CDF_CANDIDATES {
            get {
                return ResourceManager.GetString("CDF_CANDIDATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]日付が入力されていません。[e]Date field is empty.[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_DATE_EMPTY {
            get {
                return ResourceManager.GetString("CDF_DATE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]{0} 以前の日付を指定してください。[e]Please specify a date before {0}.[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_DATE_MAX {
            get {
                return ResourceManager.GetString("CDF_DATE_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]{0} 以降の日付を指定してください。[e]Please specift a date since {0}.[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_DATE_MIN {
            get {
                return ResourceManager.GetString("CDF_DATE_MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]日付として認識できない文字列が入力されています。[e]Can&apos;t recognize as a valid date.[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_DATE_NOTDATE {
            get {
                return ResourceManager.GetString("CDF_DATE_NOTDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]全件表示 ({0} 件)[e]Total ({0} entities)[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_DL_ALL {
            get {
                return ResourceManager.GetString("CDF_DL_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]ダウンロード[e]Download[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_DOWNLOAD {
            get {
                return ResourceManager.GetString("CDF_DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]日時が入力されていません。[e]Date and Time are empty.[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_DT_EMPTY {
            get {
                return ResourceManager.GetString("CDF_DT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]{0} 以前の日時を指定してください。[e]Please specify a date and a time before {0}.[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_DT_MAX {
            get {
                return ResourceManager.GetString("CDF_DT_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]{0} 以降の日時を指定してください。[e]Please specify a date and a time since {0}.[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_DT_MIN {
            get {
                return ResourceManager.GetString("CDF_DT_MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]日時として認識できない文字列が入力されています。[e]Can&apos;t recognize as a valid date and a time.[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_DT_NOTDT {
            get {
                return ResourceManager.GetString("CDF_DT_NOTDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]記入例[e]Example[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_EXAMPLE {
            get {
                return ResourceManager.GetString("CDF_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]ＭＳ ゴシック[e]MS Gothic[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_GOTHIC {
            get {
                return ResourceManager.GetString("CDF_GOTHIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]データ構造のフィールド数が 1 でありません。[e]The number of fields of data structures is not one.[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_GRID_ERROR_1 {
            get {
                return ResourceManager.GetString("CDF_GRID_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]データ構造がリストでありません。[e]The data structure is not a list.[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_GRID_ERROR_2 {
            get {
                return ResourceManager.GetString("CDF_GRID_ERROR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]数値は {0} 以下を指定してください。[e]The value must be {0} or less.[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_INT_MAX {
            get {
                return ResourceManager.GetString("CDF_INT_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]数値は {0} 以上を指定してください。[e]The value must be {0} or more.[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_INT_MIN {
            get {
                return ResourceManager.GetString("CDF_INT_MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]整数以外の文字が入力されています。[e]The value can&apos;t be recognized as an integer.[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_INT_NOT_NUMBER_CHAR {
            get {
                return ResourceManager.GetString("CDF_INT_NOT_NUMBER_CHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]数値が正しく入力されていません。[e]The value can&apos;t be recognized as a formal figure.[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_INT_NOTINTEGER {
            get {
                return ResourceManager.GetString("CDF_INT_NOTINTEGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]データ &quot;{0}&quot; はこのリストでは不正です。[e]The data &quot;{0}&quot; is invalid at this list.[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_INVALID {
            get {
                return ResourceManager.GetString("CDF_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]メールアドレスが不正です。[e]The mail address is invalid.[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_INVALID_EMAIL {
            get {
                return ResourceManager.GetString("CDF_INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]【 {0} 個目の項目 (合計 {1} 個中) - {2} 】[e]Item of piece {0} (Total: {1} entities) - {2}[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_LIST_FORMAT {
            get {
                return ResourceManager.GetString("CDF_LIST_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CdfClass 属性が正しく指定されていないクラス %s が指定されました。 的本地化字符串。
        /// </summary>
        internal static string CDF_NO_CDFCLASS {
            get {
                return ResourceManager.GetString("CDF_NO_CDFCLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 %s 項目に %s 属性が 1 つ指定されていません。 的本地化字符串。
        /// </summary>
        internal static string CDF_NO_SINGLE_ATT {
            get {
                return ResourceManager.GetString("CDF_NO_SINGLE_ATT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 %s 項目のジェネリック型が 1 つ指定されていません。 的本地化字符串。
        /// </summary>
        internal static string CDF_NO_SINGLE_GENERIC_TYPE {
            get {
                return ResourceManager.GetString("CDF_NO_SINGLE_GENERIC_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]項目なし[e]No Entities[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_NOITEM {
            get {
                return ResourceManager.GetString("CDF_NOITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]項目が選択されていません。[e]You have to select an entity.[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_NOT_SELECTED {
            get {
                return ResourceManager.GetString("CDF_NOT_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]正しく選択されていません。[e]You have to select correctly.[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_NOT_SELECTED_2 {
            get {
                return ResourceManager.GetString("CDF_NOT_SELECTED_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]ページ {0}[e]Page {0}[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_PAGING_FORMAT_1 {
            get {
                return ResourceManager.GetString("CDF_PAGING_FORMAT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]最新 {0} 件[e]Latest: {0} entities[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_PAGING_FORMAT_2 {
            get {
                return ResourceManager.GetString("CDF_PAGING_FORMAT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j] ({2}: {0} ～ {1})[e] ({2}: {0} - {1})[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_PAGING_HELPSTR_FORMAT {
            get {
                return ResourceManager.GetString("CDF_PAGING_HELPSTR_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]▼選択してください▼[e]- Please Select Here -[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_PLEASE_SELECT {
            get {
                return ResourceManager.GetString("CDF_PLEASE_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]削除[e]Delete[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_REMOVE {
            get {
                return ResourceManager.GetString("CDF_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]この項目を削除します。よろしいですか？[e]Do you want to delete this entity?[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_REMOVEMSG {
            get {
                return ResourceManager.GetString("CDF_REMOVEMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]項目が 1 件も見つかりませんでした。[e]No entity is found.[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_ROW_EMPTY {
            get {
                return ResourceManager.GetString("CDF_ROW_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]▽選択可能[e]- Selectable -[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_SELECTABLE {
            get {
                return ResourceManager.GetString("CDF_SELECTABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]▲「{0}」でソート[e]Sort by &quot;{0}&quot; Ascending[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_SORT_1 {
            get {
                return ResourceManager.GetString("CDF_SORT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]▼「{0}」で逆ソート[e]Sort by &quot;{0}&quot; Descending[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_SORT_2 {
            get {
                return ResourceManager.GetString("CDF_SORT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]▲標準のソート[e]Standard Ascending Sort[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_SORT_DEF1 {
            get {
                return ResourceManager.GetString("CDF_SORT_DEF1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]▼標準の逆ソート[e]Standard Descending Sort[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_SORT_DEF2 {
            get {
                return ResourceManager.GetString("CDF_SORT_DEF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]使用できない文字が含まれています。[e]There are some invalid characters which can&apos;t be used.[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_STRING_INVALIDCHAR {
            get {
                return ResourceManager.GetString("CDF_STRING_INVALIDCHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]文字数は {0} 以下にする必要があります。[e]The number of characters must be {0} or less.[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_STRING_MAX {
            get {
                return ResourceManager.GetString("CDF_STRING_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]文字を {0} 文字以上入力する必要があります。[e]The number of characters must be {0} or more.[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_STRING_MIN {
            get {
                return ResourceManager.GetString("CDF_STRING_MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]改行文字を含めることはできません。[e]There must not be any New-Line characters in the string.[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_STRING_NOLINE {
            get {
                return ResourceManager.GetString("CDF_STRING_NOLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]表示不可能な文字コードが含まれています。[e]There must not be any Non-Printable characters in the string.[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_STRING_NONPRINTABLE {
            get {
                return ResourceManager.GetString("CDF_STRING_NONPRINTABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]入力いただいた内容を確認のため表示しています。内容をよくご確認ください。&lt;BR&gt;この内容で確定する場合は [OK] ボタンを、修正する場合は [修正する] ボタンをクリックしてください。[e]Please confirm the printed data which you input. Please read it carefully.&lt;BR&gt;If you want to commit with this data, click the &quot;OK&quot; button. Otherwise, click the &quot;Modify&quot; button.[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_TEXT_CONFIRM {
            get {
                return ResourceManager.GetString("CDF_TEXT_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]エラーが発生しました。内容を見直してください。修正する場合は [修正する] ボタンをクリックしてください。[e]An error has been occurred. Please confirm the fields. To modify it, click the &quot;Modify&quot; button.[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_TEXT_CONFIRM_ERROR {
            get {
                return ResourceManager.GetString("CDF_TEXT_CONFIRM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]入力が完了したら [OK] ボタンを、入力をキャンセルするには [キャンセル] ボタンをクリックしてください。[e]Please click the &quot;OK&quot; button after you complete filling all necessary fields. To cancel inputting, click the &quot;Cancel&quot; button.[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_TEXT_OK {
            get {
                return ResourceManager.GetString("CDF_TEXT_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]時刻が入力されていません。[e]Time is empty.[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_TIME_EMPTY {
            get {
                return ResourceManager.GetString("CDF_TIME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]{0} 以前の時刻を指定してください。[e]Please specify a time before {0}.[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_TIME_MAX {
            get {
                return ResourceManager.GetString("CDF_TIME_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]{0} 以降の時刻を指定してください。[e]Please specify a time after {0}.[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_TIME_MIN {
            get {
                return ResourceManager.GetString("CDF_TIME_MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]時刻として認識できない文字列が入力されています。[e]Can&apos;t recognize as a valid time.[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_TIME_NOTTIME {
            get {
                return ResourceManager.GetString("CDF_TIME_NOTTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [j]フィールド %s の型 %s がサポートされていません。[e]In the field &quot;%s&quot;, the type &quot;%s&quot; is not supported.[/] 的本地化字符串。
        /// </summary>
        internal static string CDF_UNSUPPORTED {
            get {
                return ResourceManager.GetString("CDF_UNSUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item 的本地化字符串。
        /// </summary>
        internal static string CMD_CT_STD_COLUMN_1 {
            get {
                return ResourceManager.GetString("CMD_CT_STD_COLUMN_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value 的本地化字符串。
        /// </summary>
        internal static string CMD_CT_STD_COLUMN_2 {
            get {
                return ResourceManager.GetString("CMD_CT_STD_COLUMN_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The date and time specification is invalid. \nThe date and time must be in the same format as &quot;2005/10/08 19:30:00&quot; where 6 integers are specified, representing year/month/day hour:minute:second separated by forward slashes, a space and then colons. Specify 4 digits for the year. 的本地化字符串。
        /// </summary>
        internal static string CMD_EVAL_DATE_TIME_FAILED {
            get {
                return ResourceManager.GetString("CMD_EVAL_DATE_TIME_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must specify an integer that is not less than 1. 的本地化字符串。
        /// </summary>
        internal static string CMD_EVAL_INT {
            get {
                return ResourceManager.GetString("CMD_EVAL_INT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must specify an integer in the range from %u to %u for the value. 的本地化字符串。
        /// </summary>
        internal static string CMD_EVAL_MIN_MAX {
            get {
                return ResourceManager.GetString("CMD_EVAL_MIN_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot make a blank specification. 的本地化字符串。
        /// </summary>
        internal static string CMD_EVAL_NOT_EMPTY {
            get {
                return ResourceManager.GetString("CMD_EVAL_NOT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port number is invalid. Specify a port number that is within the range of 1 to 65535. 的本地化字符串。
        /// </summary>
        internal static string CMD_EVAL_PORT {
            get {
                return ResourceManager.GetString("CMD_EVAL_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The string contains unusable characters. 的本地化字符串。
        /// </summary>
        internal static string CMD_EVAL_SAFE {
            get {
                return ResourceManager.GetString("CMD_EVAL_SAFE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 %S command - %s 的本地化字符串。
        /// </summary>
        internal static string CMD_EXEC_MSG_NAME {
            get {
                return ResourceManager.GetString("CMD_EXEC_MSG_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file name is not specified. 的本地化字符串。
        /// </summary>
        internal static string CMD_FILE_NAME_EMPTY {
            get {
                return ResourceManager.GetString("CMD_FILE_NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot find specified file &quot;%s&quot;. 的本地化字符串。
        /// </summary>
        internal static string CMD_FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("CMD_FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can use the following %u commands: 的本地化字符串。
        /// </summary>
        internal static string CMD_HELP_1 {
            get {
                return ResourceManager.GetString("CMD_HELP_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To reference the usage for each command, input &quot;command name /?&quot; to view a help. 的本地化字符串。
        /// </summary>
        internal static string CMD_HELP_2 {
            get {
                return ResourceManager.GetString("CMD_HELP_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameters: 的本地化字符串。
        /// </summary>
        internal static string CMD_HELP_ARGS {
            get {
                return ResourceManager.GetString("CMD_HELP_ARGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Purpose: 的本地化字符串。
        /// </summary>
        internal static string CMD_HELP_DESCRIPTION {
            get {
                return ResourceManager.GetString("CMD_HELP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description: 的本地化字符串。
        /// </summary>
        internal static string CMD_HELP_HELP {
            get {
                return ResourceManager.GetString("CMD_HELP_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help for command &quot;%S&quot; 的本地化字符串。
        /// </summary>
        internal static string CMD_HELP_TITLE {
            get {
                return ResourceManager.GetString("CMD_HELP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Usage: 的本地化字符串。
        /// </summary>
        internal static string CMD_HELP_USAGE {
            get {
                return ResourceManager.GetString("CMD_HELP_USAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;IP アドレス/サブネットマスク&quot; の形式で指定してください。
        ///IP アドレスは 192.168.0.1 のように 10 進数をドットで区切って指定します。サブネットマスクは 255.255.255.0 のように 10 進数をドットで区切って指定するか、24 のように先頭からのビット長を 10 進数で指定できます。
        ///単一のホストを指定するには、サブネットマスクを 255.255.255.255 または 32 として指定します。
        ///(例)
        /// 192.168.0.1/24
        /// 192.168.0.1/255.255.255.0
        ///192.168.0.5/255.255.255.255
        ///
        /// 的本地化字符串。
        /// </summary>
        internal static string CMD_PARSE_IP_SUBNET_ERROR_1 {
            get {
                return ResourceManager.GetString("CMD_PARSE_IP_SUBNET_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定された IP アドレスはネットワークアドレスではありません。 的本地化字符串。
        /// </summary>
        internal static string CMD_PARSE_IP_SUBNET_ERROR_2 {
            get {
                return ResourceManager.GetString("CMD_PARSE_IP_SUBNET_ERROR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter a value:  的本地化字符串。
        /// </summary>
        internal static string CMD_PROMPT {
            get {
                return ResourceManager.GetString("CMD_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input the port number:  的本地化字符串。
        /// </summary>
        internal static string CMD_PROMPT_PORT {
            get {
                return ResourceManager.GetString("CMD_PROMPT_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no description for this command. 的本地化字符串。
        /// </summary>
        internal static string CMD_UNKNOWM {
            get {
                return ResourceManager.GetString("CMD_UNKNOWM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no command execution example. 的本地化字符串。
        /// </summary>
        internal static string CMD_UNKNOWN_ARGS {
            get {
                return ResourceManager.GetString("CMD_UNKNOWN_ARGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no detailed description for this command. If you would like to know more detail about this command, please refer to the manual or online documentation. 的本地化字符串。
        /// </summary>
        internal static string CMD_UNKNOWN_HELP {
            get {
                return ResourceManager.GetString("CMD_UNKNOWN_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no description for this parameter. 的本地化字符串。
        /// </summary>
        internal static string CMD_UNKNOWN_PARAM {
            get {
                return ResourceManager.GetString("CMD_UNKNOWN_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;%S&quot;: The command-name is ambiguous. 的本地化字符串。
        /// </summary>
        internal static string CON_AMBIGUOUS_CMD {
            get {
                return ResourceManager.GetString("CON_AMBIGUOUS_CMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified command name matches the following multiple commands. 的本地化字符串。
        /// </summary>
        internal static string CON_AMBIGUOUS_CMD_1 {
            get {
                return ResourceManager.GetString("CON_AMBIGUOUS_CMD_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please re-specify the command name more strictly. 的本地化字符串。
        /// </summary>
        internal static string CON_AMBIGUOUS_CMD_2 {
            get {
                return ResourceManager.GetString("CON_AMBIGUOUS_CMD_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;%S&quot;: The parameter name is ambiguous. 的本地化字符串。
        /// </summary>
        internal static string CON_AMBIGUOUS_PARAM {
            get {
                return ResourceManager.GetString("CON_AMBIGUOUS_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified parameter name matches with the following parameters that can be specified as a parameter of command &quot;%S&quot;. 的本地化字符串。
        /// </summary>
        internal static string CON_AMBIGUOUS_PARAM_1 {
            get {
                return ResourceManager.GetString("CON_AMBIGUOUS_PARAM_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please re-specify the parameter name more strictly. 的本地化字符串。
        /// </summary>
        internal static string CON_AMBIGUOUS_PARAM_2 {
            get {
                return ResourceManager.GetString("CON_AMBIGUOUS_PARAM_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: Unable to open the specified input file &quot;%s&quot;. 的本地化字符串。
        /// </summary>
        internal static string CON_INFILE_ERROR {
            get {
                return ResourceManager.GetString("CON_INFILE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The commands written in the file &quot;%s&quot; will be used instead of input from keyboard. 的本地化字符串。
        /// </summary>
        internal static string CON_INFILE_START {
            get {
                return ResourceManager.GetString("CON_INFILE_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The parameter &quot;/%S&quot; has been specified. It is not possible to specify this parameter when using the command &quot;%S&quot;. Input &quot;%S /HELP&quot; to see the list of what parameters can be used. 的本地化字符串。
        /// </summary>
        internal static string CON_INVALID_PARAM {
            get {
                return ResourceManager.GetString("CON_INVALID_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: Unable to create the specified output file &quot;%s&quot;. 的本地化字符串。
        /// </summary>
        internal static string CON_OUTFILE_ERROR {
            get {
                return ResourceManager.GetString("CON_OUTFILE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The message output to the console will be saved in the file &quot;%s&quot;. 的本地化字符串。
        /// </summary>
        internal static string CON_OUTFILE_START {
            get {
                return ResourceManager.GetString("CON_OUTFILE_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;%S&quot;: Command not found. You can use the HELP command to view a list of the available commands. 的本地化字符串。
        /// </summary>
        internal static string CON_UNKNOWN_CMD {
            get {
                return ResourceManager.GetString("CON_UNKNOWN_CMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [EOF] 的本地化字符串。
        /// </summary>
        internal static string CON_USER_CANCEL {
            get {
                return ResourceManager.GetString("CON_USER_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The command was canceled. 的本地化字符串。
        /// </summary>
        internal static string CON_USER_CANCELED {
            get {
                return ResourceManager.GetString("CON_USER_CANCELED", resourceCulture);
            }
        }
    }
}
